### ISSUE TITLE
Building for OSX gives "undefined: New" error

### ISSUE THREAD

**Issue by stephenliberty** [dpotapov/go-spnego#1]
Quite literally the title. Can't figure this one out, but if you build for OSX (so.. darwin / amd64) the following error occurs: 

`../../go/src/github.com/dpotapov/go-spnego/transport.go:24:14: undefined: New`

I assume there's something hardcoded that needs to be updated but I don't know where it is.

**Comment by dpotapov** [comment]
Just made a commit that should resolve it for macOS: c2c609116ad04b25367e2789f273aaf8d1c263da
