### ISSUE TITLE
Consider updating to a newer version of gokrb5

### ISSUE THREAD

**Issue by bk2204** [dpotapov/go-spnego#2]
The version of `gopkg.in/jcmturner/gokrb5.v5` used here doesn't contain `go.sum` entries for all its values and consequently it can't be built with Go 1.16.  Is it possible you could update to v8 so that folks can use this on Go 1.16?

**Comment by dpotapov** [comment]
sure, I think I can do that

**Comment by dpotapov** [comment]
Apparently, v5 builds with go1.16 just fine: https://github.com/dpotapov/go-spnego/pull/3/checks?check_run_id=2096706180

Going to update to v8 anyway.
